# -*- coding: utf-8 -*-
"""ASR Evaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tbdwxr_dQO-JdVhnLKACq1URBwDlGXMe
"""

from collections.abc import Iterable
from pathlib import Path
import os
import json
import sys
import importlib
from datetime import datetime
from asr_ouput import write_asr_json, write_asr_csv, write_asr_txt

# output_base_dir = Path("output")
# load_scripts_base_dir = Path("/app/load_scripts")

# def make_metrics(predictions: Iterable[str], references: Iterable[str]):
#     wer_evaluator = evaluate.load("wer")

#     wer = wer_evaluator.compute(predictions=predictions,  references=references)

#     return wer

def predict_asr(**kwargs):

    model_id = kwargs.get("model_id")
    input_path = kwargs.get("input_path", None)
    output_base_dir = kwargs.get("output_base_dir", "/scripts/output")
    output_types = kwargs.get("output_types", ["json"])

    output_dir = Path(output_base_dir) / (model_id.replace("/", "_"))
    # output_dir = os.path.join(output_base_dir, (model_id.replace("/", "_") + " on " + dataset_id.replace("/", "_")))
    output_dir.mkdir(parents=True, exist_ok=True)

    ## Prepare files
    input_files_path = Path(input_path)
    files = [item.name for item in input_files_path.iterdir() if item.is_file()]

    # sys.path.append(str(load_scripts_base_dir / "models" / model_id))
    # import model_loader
    print("LOADING MODEL")
    model_id_path = model_id.replace("/", ".")
    model_loader = importlib.import_module(f"load_scripts.models.{model_id_path}.model_loader")
    model = model_loader.load()
    print("MODEL LOADED")

    # Make predictions
    print("MAKING PREDICTIONS")
    predictions = []
    for file in files:
        filepath = f"{input_files_path}/{file}"
        print(filepath)
        input()
        pred = model(filepath)
        predictions.append(pred)

    # predictions = [pred["text"] for pred in predictions]
    # print(f"Len of predictions: {len(predictions)}")

    # output_dir.mkdir(exist_ok=True)

    with open(output_dir / "metadata.json", "w") as out_file:
        json.dump({
            "model_id": model_id,
            "input_path": input_path
        }, out_file)

    for prediction in predictions:
        write_asr_json(prediction, output_dir)
        write_asr_csv(prediction, output_dir)
        write_asr_txt(prediction, output_dir)
    # prediction_output = {
    #     "predictions": predictions,
    # }

    # with open(output_dir / "predictions.json", "w") as out_file:
    #     json.dump(prediction_output, out_file)
    # print(f"Outputted to: {output_dir}/predictions.json")


def predict_asr_dataset(**kwargs):

    model_id = kwargs.get("model_id")
    dataset_id = kwargs.get("dataset_id")
    dataset_config_name = kwargs.get("dataset_config_name")
    dataset_split = kwargs.get("dataset_split")
    output_base_dir = kwargs.get("output_base_dir", "/scripts/output")

    output_dir = Path(output_base_dir) / (model_id.replace("/", "_") + "_on_" + dataset_id.replace("/", "_"))
    # output_dir = os.path.join(output_base_dir, (model_id.replace("/", "_") + " on " + dataset_id.replace("/", "_")))
    output_dir.mkdir(parents=True, exist_ok=True)
    print(output_dir)
    input()

    # Load dataset and model
    # sys.path.append(str(load_scripts_base_dir / "datasets" / dataset_id))
    print("LOADING DATASET")
    dataset_id_path = dataset_id.replace("/", ".")
    dataset_loader = importlib.import_module(f"load_scripts.datasets.{dataset_id_path}.dataset_loader")
    dataset = dataset_loader.load(dataset_config_name, dataset_split)
    print("DATASET LOADED")

    # sys.path.append(str(load_scripts_base_dir / "models" / model_id))
    # import model_loader
    print("LOADING MODEL")
    model_id_path = model_id.replace("/", ".")
    model_loader = importlib.import_module(f"load_scripts.models.{model_id_path}.model_loader")
    model = model_loader.load()
    print("MODEL LOADED")

    # Make predictions
    print("MAKING PREDICTIONS")
    predictions = model(dataset.select_columns("audio"))

    predictions = [pred["text"] for pred in predictions]
    print(f"Len of predictions: {len(predictions)}")

    # output_dir.mkdir(exist_ok=True)
    with open(output_dir / "metadata.json", "w") as out_file:
        json.dump({
            "model_id": model_id,
            "dataset_id": dataset_id,
            "dataset_config_name": dataset_config_name,
            "dataset_split": dataset_split,
        }, out_file)

    prediction_output = {
        "predictions": predictions,
    }

    with open(output_dir / "predictions.json", "w") as out_file:
        json.dump(prediction_output, out_file)
    print(f"Outputted to: {output_dir}/predictions.json")

if __name__ == "__main__":
    pass